# Generated by Django 5.0.6 on 2024-06-15 06:27

import pdfs.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfs', '0005_remove_pdf_session_remove_pdf_some_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf',
            name='file',
            field=models.FileField(storage=pdfs.storage.OverwriteStorage(), upload_to='pdfs/'),
        ),
    ]
