# Generated by Django 5.0.6 on 2024-06-15 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdfs', '0002_pdf_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdf',
            name='session',
        ),
    ]
