# Generated by Django 5.0.6 on 2024-06-15 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_view', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PDF',
        ),
    ]
