# Generated by Django 5.0.6 on 2024-06-15 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdfs', '0004_pdf_session_pdf_some_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdf',
            name='session',
        ),
        migrations.RemoveField(
            model_name='pdf',
            name='some_field',
        ),
    ]
